[phases.setup]
  nixPkgs = ['bun', 'rustc', 'cargo']
  aptPkgs = ['build-essential']

[phases.build]
  cmds = [
    'cd astro_site && bun install',
    'cd astro_site && bun run build',
    'cargo build --release --jobs 1'
  ]

[start]
  cmd = './target/release/website'
  port = 8000
