[debug]
port = 8080

[default.databases.javierie]
url = "postgres://postgres:password@127.0.0.1:5432/javierie"
min_connections = 64
max_connections = 1024
connect_timeout = 5
idle_timeout = 120
ip_header = "X-Real-IP"

